# Super simple formula; just install the package.
# Ultimately, this formula assumes the pkg installer was generated by a McAfee
# ePolicy Orchestrator, and so the necessary configuration is embedded in the
# installer.

install-mcafee-agent:
  pkg.installed:
    - name: 'McAfee Agent'
    - allow_updates: True
    - require_in:
      - service: mcafee-agent-macmnsvc-service
      - service: mcafee-agent-masvc-service

mcafee-agent-macmnsvc-service:
  service.running:
    - name: 'macmnsvc'

mcafee-agent-masvc-service:
  service.running:
    - name: 'masvc'
