{%- from 'mcafee-agent-windows/map.jinja' import mcafee with context %}

# Super simple formula; just install the package.
# Ultimately, this formula assumes the pkg installer was generated by a McAfee
# ePolicy Orchestrator, and so the necessary configuration is embedded in the
# installer.

install-mcafee-agent:
  pkg.installed:
    - name: {{ mcafee.package }}
{%- if mcafee.version %}
    - version: {{ mcafee.version }}
{%- endif %}
    - allow_updates: True
